### PR TITLE
Update fact_system.md

### PR DESCRIPTION
**Pull request by mnumanuyar**
I had a hard time figuring out how to add custom facts, but feel free to decline if you think they are too obivious. Also I am not sure if the  part related to custom builds should be here or in custom build part.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @mnumanuyar !
@DonLakeFlyer This looks really useful to me, but I don't know enough about QGC to approve.

**Comment by DonLakeFlyer** [comment]
All correct information and certainly can't hurt. Would be nice at least link to FirmwarePlugin.h as well. Since that header has comments which doc all of these methods.

**Comment by hamishwillee** [comment]
@mnumanuyar Can you please create that link @DonLakeFlyer refers to in https://github.com/mavlink/qgc-dev-guide/pull/108#issuecomment-663875825

**Comment by mnumanuyar** [comment]
done @hamishwillee

**Comment by hamishwillee** [comment]
Thanks @mnumanuyar ! Merged.

**Pull request merged**
