### PR TITLE
Add information on how to get support

### PR DESCRIPTION
**Pull request by hamishwillee**
This adds a support section to the home page. This doc is still fairly "thin" so it makes sense to explain how to get help early.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Did you know there was a whole "Support" page in there?

**Comment by hamishwillee** [comment]
Where? Can't find one in the DEV guide: https://dev.qgroundcontrol.com/en/ - though there is in the user guide.

**Comment by DonLakeFlyer** [comment]
Ah, dev guide, Sorry

**Comment by hamishwillee** [comment]
No worries. I'm merging this. We can move it later if you like.

**Pull request merged**
