### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by madflower**
You need gstreamer development packages to build on Fedora

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @madflower 

@DonLakeFlyer I think it is actually a good idea to also add the gstreamer dependency info here. I pulled in the GStreamer dependencies for Ubuntu from the installation page - would there be anything else?
- I haven't verified the Fedora dependencies. Would be good to get independent verification.

Thoughts?

**Comment by DonLakeFlyer** [comment]
That means it is duplicated here: https://github.com/mavlink/qgroundcontrol/blob/master/src/VideoReceiver/README.md which is badness and will get out of sync instantly. What I would do is add a #4 to this section and move up the video streaming link so people see it.

**Comment by DonLakeFlyer** [comment]
Also FYI but I think the video gstreamer instructions for installing packages is out of date with the latest changes. The crazy sed script thing doesn't work I don't think. But anyway there is where the main docs should be. An I would guess that Fedora isn't going to be any different than Ubuntu which is where the docs were created from. But who knows!

**Comment by hamishwillee** [comment]
@DonLakeFlyer I agree.  I moved the optional section up to be the 4th list item ( Ignore the "1" prefix - this is auto-numbered). Had there been more options I would have just linked down to the section. Let me know if you are OK with this.

Who is responsible for the Gstreamer instructions - now linked? If we think they might be wrong would be good to get retested.

@madflower FYI, you could test the instructions for Fedora if you liked.

**Comment by hamishwillee** [comment]
Merging. I think this is an improvement. It would be good to keep the linked instructions up to date though.

**Pull request merged**
