### PR TITLE
Add globalPlanAltitudeMode to mission plan json docs.

### PR DESCRIPTION
**Pull request by dlech**
This property was added in https://github.com/mavlink/qgroundcontrol/commit/1c2579a7799d6e81d92bd25a58acab23d9b82e0c

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks! Was there a corresponding update the file version (and if not, was that intentional)?

@DonLakeFlyer Looks good to me. You good with this?

**Comment by DonLakeFlyer** [comment]
Sure. Looks correct to me if that's what is happening in Plan.

**Comment by dlech** [comment]
> Was there a corresponding update the file version (and if not, was that intentional)?

I don't know the history of the file format, but the commit I linked is from almost 3 years ago, so I suspect it is de-facto standard as part of the current version by now.

**Comment by hamishwillee** [comment]
Thanks!

**Pull request merged**
